version: '3.7'

services:
  app:
    environment:
      - NODE_ENV=production
      - ENV_PATH=../../../run/secrets/.env
    build: .
    ports:
      - 3000:3000
    secrets:
      - .env

secrets:
  .env:
    file: .env
